//getting the actionType 
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'INSERT_PROFILE_FAILURE';

//create poll action
export const CREATE_POLL_REQUEST = 'CREATE_POLL_REQUEST';
export const CREATE_POLL_SUCCESS = 'CREATE_POLL_SUCCESS';
export const CREATE_POLL_FAILURE = 'CREATE_POLL_FAILURE';

//load poll actions
export const LOAD_POLLS_REQUEST = 'LOAD_POLLS_REQUEST';
export const LOAD_POLLS_FAILURE = 'LOAD_POLLS_FAILURE';
export const LOAD_POLLS_SUCCESS = 'LOAD_POLLS_SUCCESS';

//load single poll 
export const LOAD_POLL = "LOAD_POLL";
export const LOAD_POLL_SUCCESS = "LOAD_POLL_SUCCESS";
export const LOAD_POLL_FAILURE = "LOAD_POLL_FAILURE";

//remove poll action
export const REMOVE_POLL_REQUEST = 'REMOVE_POLL_REQUEST';
export const REMOVE_POLL_SUCCESS = 'REMOVE_POLL_SUCCESS';
export const REMOVE_POLL_FAILURE = 'REMOVE_POLL_FAILURE';